### ISSUE TITLE
Test failing on Linux on branch v1.0

### ISSUE THREAD

**Issue by vokiel** [oleq/nodeprompt#12]
**ENV**
```
$ echo $BASH_VERSION
4.3.48(1)-release
```
```
$ npm -v
3.10.10
```

```
$ node -v
v6.11.1
```

```
$ git --version
git version 2.7.4
```

**Failing tests log**

```
$ npm test

> nodeprompt@1.0.0 test /home/vokiel/bin/nodeprompt
> mocha



  _getPath()
    ✓ returns path with default config (out of home)
    ✓ returns path with default config (in home)
    ✓ returns path with custom config

  _getStatus()
    ✓ works when no remote
    ✓ works when remote
    ✓ works when not clean
    ✓ works when detached or rebasing
    ✓ works when repo inited

  Nodeprompt
    constructor
      ✓ provides #model
      ✓ provides #styles
      config
        1) provides the default #config
        ✓ accepts a custom config (full)
        2) accepts a custom config (partial)

  print()
    3) generates PS1 when not Git repository
    4) generates PS1 when repository just inited
    5) generates PS1 when staged, not staged, deleted, untracked
    6) generates PS1 when detached
    7) generates PS1 while merging
    8) generates PS1 while rebasing
    9) generates PS1 while bisecting
    10) generates PS1 when branch is ahead
    11) generates PS1 when branch is behind
    12) generates PS1 when branch has diverged
    13) generates no PS1 when in .git directory
    14) generates no PS1 when in .git/* subfolder
    15) generates no PS1 when in .git/* subfolder (letter case)
    16) generates PS1 when in folder containing ".git" string

  styles
    ✓ are defined as functions


  12 passing (560ms)
  16 failing

  1) Nodeprompt
       constructor
         config
           provides the default #config:

      AssertionError: expected '$' to equal '>'
      + expected - actual

      -$
      +>
      
      at Context.it (test/nodeprompt.js:18:36)                                                                                                                                                                       

  2) Nodeprompt
       constructor
         config
           accepts a custom config (partial):

      AssertionError: expected '$' to equal '>'
      + expected - actual

      -$
      +>
      
      at Context.it (test/nodeprompt.js:48:36)                                                                                                                                                                       

  3) print()
       generates PS1 when not Git repository:

      AssertionError: expected 'undefined@undefined /path$ ' to equal 'user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:22:3)                                                                                                                                                                             

  4) print()
       generates PS1 when repository just inited:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(init) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(init) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:31:3)                                                                                                                                                                             

  5) print()
       generates PS1 when staged, not staged, deleted, untracked:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(master 44c100b +4 ?1) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(master 44c100b +4 ?1) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:42:3)                                                                                                                                                                             

  6) print()
       generates PS1 when detached:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(detached:master~1 a89567c) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(detached:master~1 a89567c) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:60:3)                                                                                                                                                                             

  7) print()
       generates PS1 while merging:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(merge:master<--test-head dcd0272 M1) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(merge:master<--test-head dcd0272 M1) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:73:3)                                                                                                                                                                             

  8) print()
       generates PS1 while rebasing:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(detached:master 76d59cb) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(detached:master 76d59cb) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:88:3)                                                                                                                                                                             

  9) print()
       generates PS1 while bisecting:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(detached:a/1234 3bf5643) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(detached:a/1234 3bf5643) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:101:3)                                                                                                                                                                            

  10) print()
       generates PS1 when branch is ahead:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(a/1234↑ 3bf5643) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(a/1234↑ 3bf5643) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:115:3)                                                                                                                                                                            

  11) print()
       generates PS1 when branch is behind:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(a/1234↓ 3bf5643) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(a/1234↓ 3bf5643) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:128:3)                                                                                                                                                                            

  12) print()
       generates PS1 when branch has diverged:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(a/1234↕ 3bf5643) user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +(a/1234↕ 3bf5643) user@host /path> 
      
      at test (test/print.js:240:45)                                                                                                                                                                                 
      at Context.it (test/print.js:141:3)                                                                                                                                                                            

  13) print()
       generates no PS1 when in .git directory:

      AssertionError: expected 'undefined@undefined /path$ ' to equal 'user@host /path> '
      + expected - actual

      -undefined@undefined /path$ 
      +user@host /path> 

      at test (test/print.js:240:45)
      at Context.it (test/print.js:154:3)

  14) print()
       generates no PS1 when in .git/* subfolder:

      AssertionError: expected 'undefined@undefined /path$ ' to equal 'user@host /path> '
      + expected - actual

      -undefined@undefined /path$
      +user@host /path>

      at test (test/print.js:240:45)
      at Context.it (test/print.js:177:3)

  15) print()
       generates no PS1 when in .git/* subfolder (letter case):

      AssertionError: expected 'undefined@undefined /path$ ' to equal 'user@host /path> '
      + expected - actual

      -undefined@undefined /path$
      +user@host /path>

      at test (test/print.js:240:45)
      at Context.it (test/print.js:192:3)

  16) print()
       generates PS1 when in folder containing ".git" string:

      AssertionError: expected 'undefined@undefined /path$ ' to equal '(master 44c100b +4 ?1) user@host /path> '
      + expected - actual

      -undefined@undefined /path$
      +(master 44c100b +4 ?1) user@host /path>

      at test (test/print.js:240:45)
      at Context.it (test/print.js:207:3)



npm ERR! Test failed.  See above for more details.
```

**Comment by oleq** [comment]
Do you use your own config in `~/.nodeprompt/config.user.js`?

**Comment by vokiel** [comment]
That was the issue. Without it all 28 tests are passing. Sorry for false alarm.
